CREATE TABLE rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT ck_rol_nombre CHECK (nombre IN ('EMPLEADO', 'TERCERIZADO', 'ADMINISTRADOR', 'RRHH'))
);

CREATE TABLE restriccion_alimenticia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(300)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    tipo_usuario VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    rol_id BIGINT NOT NULL,
    CONSTRAINT ck_usuario_tipo CHECK (tipo_usuario IN ('EMPLEADO', 'TERCERIZADO')),
    CONSTRAINT ck_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol(id) ON DELETE RESTRICT
);
CREATE INDEX idx_usuario_rol_id ON usuario(rol_id);

CREATE TABLE usuario_restriccion (
    usuario_id BIGINT NOT NULL,
    restriccion_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, restriccion_id),
    CONSTRAINT fk_usuario_restriccion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_restriccion_restriccion FOREIGN KEY (restriccion_id) REFERENCES restriccion_alimenticia(id) ON DELETE RESTRICT
);
CREATE INDEX idx_usuario_restriccion_restriccion_id ON usuario_restriccion(restriccion_id);

CREATE TABLE comida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT ck_comida_tipo CHECK (tipo IN ('ENTRADA', 'PLATO_PRINCIPAL', 'POSTRE', 'BEBIDA')),
    CONSTRAINT ck_comida_estado CHECK (estado IN ('ACTIVA', 'INACTIVA'))
);

CREATE TABLE comida_restriccion_compatible (
    comida_id BIGINT NOT NULL,
    restriccion_id BIGINT NOT NULL,
    PRIMARY KEY (comida_id, restriccion_id),
    CONSTRAINT fk_comida_restriccion_comida FOREIGN KEY (comida_id) REFERENCES comida(id) ON DELETE CASCADE,
    CONSTRAINT fk_comida_restriccion_restriccion FOREIGN KEY (restriccion_id) REFERENCES restriccion_alimenticia(id) ON DELETE RESTRICT
);
CREATE INDEX idx_comida_restriccion_restriccion_id ON comida_restriccion_compatible(restriccion_id);

CREATE TABLE temporada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    estacion VARCHAR(20) NOT NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT ck_temporada_estacion CHECK (estacion IN ('VERANO', 'OTONO', 'INVIERNO', 'PRIMAVERA')),
    CONSTRAINT ck_temporada_estado CHECK (estado IN ('BORRADOR', 'PUBLICADA', 'FINALIZADA')),
    CONSTRAINT ck_temporada_fechas CHECK (fecha_hasta >= fecha_desde)
);
CREATE UNIQUE INDEX uk_temporada_publicada ON temporada(estado) WHERE estado = 'PUBLICADA';

CREATE TABLE semana_temporada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temporada_id BIGINT NOT NULL,
    numero SMALLINT NOT NULL,
    CONSTRAINT uk_semana_temporada_numero UNIQUE (temporada_id, numero),
    CONSTRAINT ck_semana_numero CHECK (numero BETWEEN 1 AND 4),
    CONSTRAINT fk_semana_temporada FOREIGN KEY (temporada_id) REFERENCES temporada(id) ON DELETE CASCADE
);

CREATE TABLE menu_diario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_id BIGINT NOT NULL,
    dia_semana VARCHAR(10) NOT NULL,
    CONSTRAINT uk_menu_semana_dia UNIQUE (semana_id, dia_semana),
    CONSTRAINT ck_menu_dia_laborable CHECK (dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')),
    CONSTRAINT fk_menu_semana FOREIGN KEY (semana_id) REFERENCES semana_temporada(id) ON DELETE CASCADE
);

CREATE TABLE menu_comida (
    menu_id BIGINT NOT NULL,
    comida_id BIGINT NOT NULL,
    PRIMARY KEY (menu_id, comida_id),
    CONSTRAINT fk_menu_comida_menu FOREIGN KEY (menu_id) REFERENCES menu_diario(id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_comida_comida FOREIGN KEY (comida_id) REFERENCES comida(id) ON DELETE RESTRICT
);
CREATE INDEX idx_menu_comida_comida_id ON menu_comida(comida_id);

CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(36) NOT NULL,
    usuario_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    creada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_reserva_codigo UNIQUE (codigo),
    CONSTRAINT uk_reserva_usuario_fecha UNIQUE (usuario_id, fecha),
    CONSTRAINT ck_reserva_estado CHECK (estado IN ('ACTIVA', 'CANCELADA')),
    CONSTRAINT ck_reserva_dia_laborable CHECK (EXTRACT(ISODOW FROM fecha) BETWEEN 1 AND 5),
    CONSTRAINT fk_reserva_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE RESTRICT,
    CONSTRAINT fk_reserva_menu FOREIGN KEY (menu_id) REFERENCES menu_diario(id) ON DELETE RESTRICT
);
CREATE INDEX idx_reserva_menu_id ON reserva(menu_id);
CREATE INDEX idx_reserva_fecha_estado ON reserva(fecha, estado);

CREATE TABLE reserva_comida (
    reserva_id BIGINT NOT NULL,
    comida_id BIGINT NOT NULL,
    PRIMARY KEY (reserva_id, comida_id),
    CONSTRAINT fk_reserva_comida_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id) ON DELETE CASCADE,
    CONSTRAINT fk_reserva_comida_comida FOREIGN KEY (comida_id) REFERENCES comida(id) ON DELETE RESTRICT
);
CREATE INDEX idx_reserva_comida_comida_id ON reserva_comida(comida_id);

CREATE TABLE liquidacion_mensual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    anio SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    importe_total NUMERIC(12,2) NOT NULL,
    generada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_liquidacion_usuario_periodo UNIQUE (usuario_id, anio, mes),
    CONSTRAINT ck_liquidacion_anio CHECK (anio >= 2000),
    CONSTRAINT ck_liquidacion_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_liquidacion_importe CHECK (importe_total >= 0),
    CONSTRAINT fk_liquidacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE RESTRICT
);

CREATE TABLE asistencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL UNIQUE,
    administrador_id BIGINT NOT NULL,
    liquidacion_id BIGINT,
    confirmada_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_asistencia_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asistencia_administrador FOREIGN KEY (administrador_id) REFERENCES usuario(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asistencia_liquidacion FOREIGN KEY (liquidacion_id) REFERENCES liquidacion_mensual(id) ON DELETE RESTRICT
);
CREATE INDEX idx_asistencia_administrador_id ON asistencia(administrador_id);
CREATE INDEX idx_asistencia_liquidacion_id ON asistencia(liquidacion_id);
CREATE INDEX idx_asistencia_confirmada_en ON asistencia(confirmada_en);
